# Generated by Django 5.1.6 on 2025-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('customer_address', models.TextField(verbose_name='Müşteri Adresi')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Müşteri Telefonu')),
                ('checked', models.BooleanField(default=True, verbose_name='Aktif-Pasif')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
