# Generated by Django 5.1.6 on 2025-02-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contack_name',
        ),
    ]
