# Generated by Django 5.1.6 on 2025-02-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_options_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customer.customer', verbose_name='Müşteri'),
        ),
    ]
