# Generated by Django 5.1.6 on 2025-02-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_contact_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contract',
            field=models.DateTimeField(null=True, verbose_name='Sözleşme Tarihi'),
        ),
    ]
