# Generated by Django 5.1.6 on 2025-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
